name: arm64 Autotools

on: [push, pull_request]

jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y git cmake libjpeg-dev zlib1g zlib1g-dev
            apt-get install -q -y gfortran g++  yacc flex libtool autotools-dev
            apt-get install -q -y libtirpc-common libtirpc-dev libtirpc3
          run: |            
            echo ::set-output name=uname::$(uname -a)
            git clone https://github.com/HDFGroup/hdf4
            cd hdf4
            ./ci.sh

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"