name: hdf4 dev autotools icx CI

# Triggers the workflow on a call from another workflow
on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string
      build_option:
        description: "--enable-production or --disable-production"
        required: true
        type: string

permissions:
  contents: read

jobs:
  Intel_build_and_test:
    name: "Intel ${{ inputs.build_mode }}"
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@v4.1.1

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake libtool libtool-bin libaec-dev

      - name: Add oneAPI to apt
        shell: bash
        run: |
          cd /tmp
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo add-apt-repository -y "deb https://apt.repos.intel.com/oneapi all main"
      
      - name: Install oneAPI dpcpp and fortran compiler
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y intel-oneapi-compiler-dpcpp-cpp
          sudo apt install -y intel-oneapi-compiler-fortran
          sudo apt install -y intel-oneapi-mpi-devel
          echo "CC=icx" >> $GITHUB_ENV
          echo "CXX=icpx" >> $GITHUB_ENV
          echo "FC=ifx" >> $GITHUB_ENV

      - name: Install oneAPI MKL library
        shell: bash
        run: |
          sudo apt install -y intel-oneapi-mkl-devel

      - name: Autotools Configure
        shell: bash
        run: |
          source /opt/intel/oneapi/setvars.sh
          export PATH=$PATH:/opt/intel/oneapi/compiler/2023.2.1/linux/bin
          sh ./autogen.sh
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          $GITHUB_WORKSPACE/configure \
            ${{ inputs.build_option }} \
            --enable-netcdf \
            --enable-shared \
            --disable-fortran

      - name: Autotools Build
        run: |
          source /opt/intel/oneapi/setvars.sh
          export PATH=$PATH:/opt/intel/oneapi/compiler/2023.2.1/linux/bin
          make -j3
        working-directory: ${{ runner.workspace }}/build

      - name: Autotools Run Tests
        run: |
          source /opt/intel/oneapi/setvars.sh
          export PATH=$PATH:/opt/intel/oneapi/compiler/2023.2.1/linux/bin
          export SYCL_DEVICE_FILTER=opencl.cpu
          make check -j2
        working-directory: ${{ runner.workspace }}/build

      - name: Autotools Install
        run: |
          source /opt/intel/oneapi/setvars.sh
          export PATH=$PATH:/opt/intel/oneapi/compiler/2023.2.1/linux/bin
          export SYCL_DEVICE_FILTER=opencl.cpu
          make install
        working-directory: ${{ runner.workspace }}/build

#      - name: Autotools Verify Install
#        run: |
#          source /opt/intel/oneapi/setvars.sh
#          export PATH=$PATH:/opt/intel/oneapi/compiler/2023.2.1/linux/bin
#          export SYCL_DEVICE_FILTER=opencl.cpu
#          make check-install
#        working-directory: ${{ runner.workspace }}/build
